version: '3.7'
services:
  postgres:
    build:
      context: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: "pg_isready -p 5432 -h 127.0.0.1"
